services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend    
    
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres    
  
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=apps
      - POSTGRES_PASSWORD=changethis123
      - POSTGRES_DB=apps
      - POSTGRES_SERVER=localhost
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
